#!/usr/bin/env python3
"""
Test helpers and base classes for Python Generator tests
Place this in: tests/helpers/test_python_generator_base.py
"""

from pathlib import Path
from typing import Any, Dict

from coder_mcp.templates.generators.python_generator import PythonGenerator


class PythonGeneratorForTesting(PythonGenerator):
    """
    Testable version of PythonGenerator that implements abstract methods.

    This class provides a concrete implementation of PythonGenerator
    that can be instantiated in tests without requiring a workspace.
    """

    def __init__(self):
        """Initialize without calling parent constructor that needs workspace_root"""
        # Call parent constructor with a temporary path
        super().__init__(workspace_root=Path("/tmp/test"))

        # Override attributes for testing
        self._source_directory = Path("/test/src")
        self._file_header = "# Generated by coder-mcp\n\n"

    def get_source_directory(self):
        """Return the source directory path"""
        return self._source_directory

    def generate_file_header(self, title: str, description: str = "") -> str:
        """Generate a file header comment"""
        if description:
            return f"# {title}\n# {description}\n\n"
        return f"# {title}\n\n"

    def write_file(self, path: Path, content: str) -> Dict[str, Any]:
        """
        Write content to a file.
        This is typically mocked in tests.
        """
        # Default implementation for tests - usually mocked
        return {
            "path": str(path),
            "purpose": f"Generated {self.get_language_name()} file",
            "language": self.get_language_name(),
            "size": len(content),
        }
