# YAMLlint configuration for coder-mcp

extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'yes', 'no', 'on', 'off']
    check-keys: false
  comments:
    min-spaces-from-content: 2
  document-start:
    present: false
  indentation:
    spaces: 2
    indent-sequences: true
  key-duplicates: enable
  new-line-at-end-of-file: enable
  trailing-spaces: enable

ignore: |
  .venv/
  venv/
  .git/
  node_modules/
  *.egg-info/
  __pycache__/
